PUT http://localhost:8080/events/2
Content-Type: application/json

{
    "title": "Test event updated ",
    "description": "Description of the event updated",
    "location": "TestLocation updated",
    "dateTime" : "2025-01-01T15:30:00.000Z" 
}